export default function GetAllData(t:any){
    return [
        {
            "image":"/img/hashira/DSC03093.jpg",
            "title":t("item1"),
            "desc":t("item1Desc"),
        },
        {
            "image":"/img/hashira/DSC04481.jpg",
            "title":t("item2"),
            "desc":t("item2Desc")
        },
        {
            "image":"/img/hashira/att.7_HWtZQBw_M5sE-_vdGJCteps-zlZHGzsymjwg-qLXE.JPG",
            "title":t("item3"),
            "desc":t("item3Desc")
        },
        {
            "image":"/img/hashira/7a5e452c-ca8a-4ac6-aa93-6691b9a02b99.jpg",
            "title":t("item4"),
            "desc":t("item4Desc")
        },
        {
            "image":"/img/hashira/DSC03966.jpg",
            "title":t("item5"),
            "desc":t("item5Desc")
        },
        {
            "image":"/img/hashira/bf526fa8-dcc3-4530-9fa7-5555f4594b7b.jpg",
            "title":t("item6"),
            "desc":t("item6Desc")
        }
    ]
}