export function getData(){
    return [
        {
            number:1,
            title:"Welding",
            description:"WeldingDesc",
            videoId:"f5_XCvXz-e4",
            image1:"/img/skill/g1-img1.jpg",
            image2:"/img/skill/welding1.jpg"

        },
        {
            number:2,
            title:"Carpentry",
            description:"CarpentryDesc",
            videoId:"SeEtyq7Xusc",
            image1:"/img/skill/carpentry.jpg",
            image2:"/img/skill/carpentry3.png"
        },
        {
            number:3,
            title:"Scaffolding",
            description:"ScaffoldingDesc",
            videoId:"xPm5MUNVpk8",
            image1:"/img/skill/g3-img1.jpg",
            image2:"/img/skill/scaf1.jpg"
        },
        {
            number:4,
            title:"Masonry",
            description:"MasonryDesc",
            videoId:"bZb4obZD7Fc",
            image1:"/img/skill/g4-img1.jpeg",
            image2:"/img/skill/g4-img2.jpeg"
        },
        {
            number:5,
            title:"Painting",
            description:"PaintingDesc",
            videoId:"HBjMm8bI_jU",
            image1:"/img/skill/g5-img1.jpeg",
            image2:"/img/skill/g5-img2.jpeg"
        }
    ]
}