export function getData(){
    return [
        {
            number:1,
            title:"Welding",
            description:"WeldingDesc",
            videoId:"1vIU3R-BIDQ",
            image1:"/img/default.png",
            image2:"/img/default.png"
        },
        {
            number:2,
            title:"Carpentry",
            description:"CarpentryDesc",
            videoId:"1vIU3R-BIDQ",
            image1:"/img/default.png",
            image2:"/img/default.png"
        },
        {
            number:3,
            title:"Scaffolding",
            description:"ScaffoldingDesc",
            videoId:"1vIU3R-BIDQ",
            image1:"/img/default.png",
            image2:"/img/default.png"
        },
        {
            number:4,
            title:"Masonry",
            description:"MasonryDesc",
            videoId:"1vIU3R-BIDQ",
            image1:"/img/default.png",
            image2:"/img/default.png"
        },
        {
            number:5,
            title:"Painting",
            description:"PaintingDesc",
            videoId:"1vIU3R-BIDQ",
            image1:"/img/default.png",
            image2:"/img/default.png"
        }
    ]
}